# Generated by Django 5.1.3 on 2025-08-16 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_choices', to='quizzes.multiplechoicequestion'),
        ),
    ]
