# Generated by Django 5.1.3 on 2025-08-22 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizresult_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
