# Generated by Django 5.1.3 on 2025-08-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quizresult_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='score',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='number_of_correct_answers',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
