# Generated by Django 5.1.3 on 2025-08-23 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_quizresult_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_answers', to='quizzes.answerchoice'),
        ),
    ]
