# Generated by Django 5.1.3 on 2025-08-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_questionanswer_selected_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnswer',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='selected_choice',
            new_name='wrong_selected_choice',
        ),
    ]
