# Generated by Django 5.1.3 on 2025-08-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_rename_questionanswer_answer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='MultipleChoiceAnswer',
        ),
        migrations.RenameModel(
            old_name='AnswerChoice',
            new_name='WrongAnswerChoice',
        ),
    ]
