# Generated by Django 5.1.3 on 2025-08-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_image_alter_file_file'),
        ('quizzes', '0009_rename_answer_multiplechoiceanswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='order',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='question_text',
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='FreeResponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField(max_length=1000)),
                ('total_possible_points', models.PositiveIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frq_questions', to='quizzes.quiz')),
                ('related_subunits', models.ManyToManyField(related_name='frq_questions', to='classes.subunit')),
                ('related_units', models.ManyToManyField(related_name='frq_questions', to='classes.unit')),
            ],
        ),
        migrations.CreateModel(
            name='FreeResponseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Correct', 'Correct'), ('Incorrect', 'Incorrect')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Graded', 'Graded')], default='Pending', max_length=10)),
                ('user_answer', models.TextField(max_length=1000)),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.freeresponsequestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeResponseRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasoning_text', models.TextField(max_length=1000)),
                ('possible_points', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='quizzes.freeresponsequestion')),
            ],
        ),
        migrations.CreateModel(
            name='FreeResponseGradedRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.PositiveIntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_rubrics', to='quizzes.freeresponseanswer')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_rubrics', to='quizzes.freeresponserubric')),
            ],
        ),
    ]
