# Generated by Django 5.1.3 on 2025-08-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_remove_multiplechoicequestion_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeresponsequestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeresponsequestion',
            name='question_text',
            field=models.CharField(default='dummy question text', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='question_text',
            field=models.CharField(default='dummy question text', max_length=200),
            preserve_default=False,
        ),
    ]
