# Generated by Django 5.1.3 on 2025-08-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_remove_freeresponseanswer_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='number_of_correct_answers',
            new_name='points_awarded',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='number_of_questions',
            new_name='total_possible_points',
        ),
    ]
