# Generated by Django 5.1.3 on 2025-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_freeresponseanswer_quiz_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeresponseanswer',
            name='awarded_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
