# Generated by Django 5.1.3 on 2025-09-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_freeresponseanswer_awarded_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeresponseanswer',
            old_name='awarded_points',
            new_name='points_awarded',
        ),
    ]
