# Generated by Django 5.1.3 on 2025-09-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_rename_awarded_points_freeresponseanswer_points_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeresponsequestion',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
