# Generated by Django 5.1.1 on 2025-08-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroupmember',
            name='status',
            field=models.CharField(choices=[('Invited', 'Invited'), ('Joined', 'Joined')], default='Invited', max_length=20),
        ),
    ]
