# Generated by Django 5.1.1 on 2025-07-25 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 6, 22, 3, 967852, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
