# Generated by Django 5.1.1 on 2025-07-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0002_studygroup_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20),
        ),
    ]
