# Generated by Django 5.1.1 on 2025-07-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0003_alter_studygroup_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroupmember',
            name='status',
            field=models.CharField(choices=[('Invited', 'Invited'), ('Joined', 'Joined')], max_length=20),
        ),
    ]
