# Generated by Django 5.1.3 on 2025-05-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='class_obj',
            new_name='class_field',
        ),
    ]
