# Generated by Django 5.1.3 on 2025-08-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.ImageField(default='lopez_urban_farm.jpeg', upload_to=''),
            preserve_default=False,
        ),
    ]
