# Generated by Django 5.1.3 on 2025-05-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_class_obj_unit_class_field'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='classes', to='users.member'),
        ),
    ]
