# Generated by Django 5.1.3 on 2025-05-22 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_members'),
        ('users', '0002_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_classes', to='users.member'),
        ),
    ]
