# Generated by Django 5.1.1 on 2025-07-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_filecategory_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='join_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
