# Generated by Django 5.1.1 on 2025-07-14 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_class_join_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecategory',
            name='name',
        ),
        migrations.AlterField(
            model_name='class',
            name='join_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='class_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='subunit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='classes.subunit'),
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='classes.unit'),
        ),
    ]
