# Generated by Django 5.1.1 on 2025-07-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_filecategory_name_alter_class_join_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
