# Generated by Django 5.1.3 on 2025-05-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('member_id', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
