# Generated by Django 5.1.1 on 2025-08-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.member'),
        ),
    ]
